app_name: acsp-api
group: api

weight: 100
routes:
  1: ^/acsp/*
  2: ^/transactions/(.*)/authorised-corporate-service-provider-applications/(.*)
  3: ^/acsp-api/*
  4: ^/private/transactions/(.*)/authorised-corporate-service-provider-applications/(.*)/filings
