server:
  port: 18642
spring:
  application:
    name: acsp-api
  main:
    allow-bean-definition-overriding: true
#Below are the properties to connect to MongoDB. Replace 'collection_name' with the collection you want to access.
#  data:
#    mongodb:
#      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/collection_name}
#      collection: ${MONGODB_COLLECTION:collection_name}
management:
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health



