server:
  port: 18642
  servlet:
    context-path: /acsp-api

spring:
  application:
    name: acsp-api
  main:
    allow-bean-definition-overriding: true
#Below are the properties to connect to MongoDB. Change the collection name if needed
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/acsp}
      collection: ${MONGODB_COLLECTION:acsp}
management:
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

api:
  key: ${CHS_API_KEY}
  url: ${API_URL}

payments:
  url: ${PAYMENTS_API_URL}
ACSP01_COST: 100