package uk.gov.companieshouse.acsp.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import uk.gov.companieshouse.acsp.Exception.ServiceException;
import uk.gov.companieshouse.acsp.sdk.ApiClientService;
import uk.gov.companieshouse.api.error.ApiErrorResponseException;
import uk.gov.companieshouse.api.handler.exception.URIValidationException;
import uk.gov.companieshouse.api.handler.payment.request.PaymentCreate;
import uk.gov.companieshouse.api.model.ApiResponse;
import uk.gov.companieshouse.api.model.payment.PaymentApi;
import uk.gov.companieshouse.api.model.payment.PaymentSessionApi;
import uk.gov.companieshouse.api.model.transaction.Transaction;
import uk.gov.companieshouse.environment.EnvironmentReader;
import uk.gov.companieshouse.environment.impl.EnvironmentReaderImpl;


import java.io.IOException;

@Service
public class PaymentsService {
    private final ApiClientService apiClientService;

    @Autowired
    public PaymentsService(ApiClientService apiClientService) {
        this.apiClientService = apiClientService;
    }

    private static EnvironmentReader environmentReader = new EnvironmentReaderImpl();

    public PaymentApi createPaymentSession(String passThroughHeader, Transaction transaction) throws ServiceException {
//      below is the dummy body, resource should be the payment link generated by transactcion api
        PaymentSessionApi paymentSessionApi = new PaymentSessionApi();
        paymentSessionApi.setRedirectUri("https://cidev.aws.chdev.org/transactions/117524-754816-491724/company/10000025/confirmation");
        paymentSessionApi.setReference("company-accounts_TB32652391");
        paymentSessionApi.setResource(environmentReader.getMandatoryString("API_URL") + transaction.getLinks().getPayment());
        paymentSessionApi.setState("d7a6a1d8-0da6-4eec-9f2f-455dfa206e28");

        PaymentCreate paymentCreate = null;

        try {
            paymentCreate = apiClientService.getApiClient(passThroughHeader).payment().create("/payments", paymentSessionApi);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        ApiResponse<PaymentApi> paymentsAPI = null;

        try {
            paymentsAPI = paymentCreate.execute();
            System.out.println(" Payment Created : " + paymentsAPI.getData());
            return paymentsAPI.getData();
        } catch (URIValidationException e) {
            throw new RuntimeException(e);
        } catch (ApiErrorResponseException e) {
            throw new RuntimeException(e);
        }
    }
}
